#pragma once

#ifndef GL_CALL_H
#define GL_CALL_H

#include <glad/glad.h>

#include <format>
#include <source_location>
#include <stdexcept>

namespace gl::detail {

inline void checkGLError(
    const char* const statement,
    const std::source_location location = std::source_location::current()
) {
    GLenum error{ glGetError() };
    if (error == GL_NO_ERROR) {
        return;
    }

    std::string errorMessages{};
    do {
        switch (error) {
        case GL_INVALID_ENUM: errorMessages += "GL_INVALID_ENUM "; break;
        case GL_INVALID_VALUE: errorMessages += "GL_INVALID_VALUE "; break;
        case GL_INVALID_OPERATION: errorMessages += "GL_INVALID_OPERATION "; break;
        case GL_INVALID_FRAMEBUFFER_OPERATION: errorMessages += "GL_INVALID_FRAMEBUFFER_OPERATION "; break;
        case GL_OUT_OF_MEMORY: errorMessages += "GL_OUT_OF_MEMORY "; break;
        default: errorMessages += "Unknown OpenGL error "; break;
        }
    } while ((error = glGetError()) != GL_NO_ERROR);

    if (!errorMessages.empty()) {
        throw std::runtime_error{ std::format(R"([ {}] in "{}" at {}:{} ({}))",
            errorMessages,
            statement,
            location.file_name(),
            location.line(),
            location.function_name()
        ) };
    }
}

} // gl::detail

/**
 * @def GL_CALL(statement)
 * @brief Executes an OpenGL statement and throws on any generated OpenGL error.
 *
 * Before executing the statement, all existing OpenGL error flags are cleared.
 * After execution, all errors generated by the statement are collected and
 * reported as a single exception.
 *
 * @param statement A single OpenGL statement to execute.
 *
 * @throws std::runtime_error
 * If one or more OpenGL errors are generated by the statement.
 *
 * @note Using this macro in performance-critical paths may be expensive.
 *
 * @example
 * GL_CALL(glGenTextures(1, &m_textureId));
 */
#define GL_CALL(statement) \
    do { \
        while (glGetError() != GL_NO_ERROR) {} \
        statement; \
        ::gl::detail::checkGLError(#statement); \
    } while (false)

#endif // GL_CALL_H
